version: '3.2'
services:
  app:
    build:
      context: ./UrlSaver
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "8014:80"
      - "44314:443"
    depends_on:
      sqlServer:
        condition: service_healthy
      redis:
        condition: service_started
  prometheus:
    build: 
      context: ./Prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - app
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"   
    depends_on:
      - prometheus
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  sqlServer:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlServer
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: [
        "CMD", "/opt/mssql-tools/bin/sqlcmd", 
        "-U", "sa", 
        "-P", "${MSSQL_PASSWORD}", 
        "-Q", "SELECT \"READY\""]
      interval: 15s
      retries: 120
  prometheus-mssql-exporter:
    image: "awaragi/prometheus-mssql-exporter"
    container_name: prometheus-mssql-exporter
    restart: always
    environment:
      - SERVER=sqlServer
      - PORT=1433
      - USERNAME=sa
      - PASSWORD=${MSSQL_PASSWORD}
      - DEBUG=app
    ports:
      - "4000:4000"
    depends_on:
      sqlServer:
        condition: service_healthy
  